[versions]
versionMajor = "2"
versionMinor = "51"
versionPatch = "0"

compileSdkVersion = "35"
minimumSdkVersion = "28"
targetSdkVersion = "36"

gradleVersion = "8.6.0"

kotlin_version = "1.9.23"
kotlinx_coroutines_version = "1.7.3"
lifecycle_runtime_ktx_version = "2.6.2"
fragment_ktx_version = "1.6.2"
core_ktx_version = "1.12.0"

annotation_version = "1.7.0"
appcompat_version = "1.6.1"
fragment_version = "1.6.2"
constraintlayout_version = "2.1.4"

filament_version = "1.57.1"
arcore_version = "1.50.0"
fuel_version = "2.3.1"

material_version = '1.11.0'

thomasGorisseSceneform_version = "1.23.0"


[libraries]

gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin_version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin_version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx_coroutines_version" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx_coroutines_version" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx_coroutines_version" }

filament-filamat-android = { module = "com.google.android.filament:filamat-android", version.ref = "filament_version" }
filament-android = { module = "com.google.android.filament:filament-android", version.ref = "filament_version" }
filament-gltfio = { module = "com.google.android.filament:gltfio-android", version.ref = "filament_version" }
filament-utils = { module = "com.google.android.filament:filament-utils-android", version.ref = "filament_version" }

arcore = { module = "com.google.ar:core", version.ref = "arcore_version" }

thomasgorisse-sceneform = { module = "com.gorisse.thomas.sceneform:sceneform", version.ref = "thomasGorisseSceneform_version" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx_version" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation_version" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle_runtime_ktx_version" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat_version" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment_ktx_version" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment_version" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout_version" }

google-android-material = { module = "com.google.android.material:material", version.ref = "material_version" }

fuel-core = { module = "com.github.kittinunf.fuel:fuel", version.ref = "fuel_version" }
fuel-android = { module = "com.github.kittinunf.fuel:fuel-android", version.ref = "fuel_version" }
fuel-coroutines = { module = "com.github.kittinunf.fuel:fuel-coroutines", version.ref = "fuel_version" }
